- name: Deploy
  hosts: [localhost]
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python2
    application: finalproject
  tasks:
    - name: create instances
      include_role: 
        name: create_instance