- name: Deploy
  hosts: [localhost]
  gather_facts: false
  vars:
    application: finalproject
  pre_tasks:
    - name: Check Minikube's status.
      command: sudo minikube status
      register: minikube_status
      changed_when: false
      ignore_errors: true
    # Otherwise will start minikube
    - name: Start Minikube if it's not running.
      command: sudo minikube start --driver=none
      when: "not minikube_status.stdout or 'Running' not in minikube_status.stdout"
  tasks:
    - name: init minikube
      include_role: 
        name: check_minikube
  # post_tasks:
  #     #Example export using minikube services
  #     - name: Expose webserver on the host via Minikube.
  #       command: sudo minikube service webserver --url=true
  #       changed_when: false
  #       register: minikube_service
  #     - debug:
  #         msg: "webserver URL: {{ minikube_service['stdout_lines'][0] }}"