- name: Deploy
  hosts: [localhost]
  gather_facts: false
  vars:
    application: finalproject
    instance_ids:
      - 'i-0319d2c0cd083710b'
  pre_tasks:
    - name: Check Minikube's status.
      command: sudo minikube status
      register: minikube_status
      changed_when: false
      ignore_errors: true
    # Otherwise will start minikube
    - name: Start Minikube if it's not running.
      command: sudo minikube start --driver=none
      when: "not minikube_status.stdout or 'Running' not in minikube_status.stdout"
  tasks:
    - name: init minikube
      include_role: 
        name: check_minikube