- name: Create EC2 instances
  ec2:
    key_name: Blue_demo
    instance_type: t2.medium
    image: ami-0986c2ac728528ac2
    user_data: "{{ USERDATA }}"
    region: us-east-2
    group_id:
      - sg-08849aeba5c5e3b04
      - sg-0af22d4c57c7bc446
    wait: yes
    instance_tags:
      Name: web_server
      application: "{{ application }}"
    exact_count: 2
    count_tag:
      application: "{{ application }}"
  register: ec2_instances