- name: Create EC2 instances
  ec2:
    key_name: Blue_demo
    instance_type: t2.medium
    image: ami-0986c2ac728528ac2
    user_data: "{{ USERDATA }}"
    region: us-west-2
    wait: yes
    instance_tags:
      Name: web_server
      application: "{{ application }}"
    exact_count: 1
    count_tag:
      application: "{{ application }}"
  register: ec2_instances