- name: Get running status
  raw: sudo kubectl run webserver --generator=run-pod/v1 --image=khaledgamalelsayed/webserver  --port=80 --labels app=webserverdemo && sudo kubectl port-forward webserver 8000:80